# Generated by Django 4.2.8 on 2023-12-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0005_deneme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Yorum')),
                ('date_now', models.DateTimeField(verbose_name='Tarih - Saat')),
            ],
        ),
    ]
