# Generated by Django 4.2.8 on 2023-12-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='fullname',
            field=models.CharField(max_length=50, null=True, verbose_name='Ad - Soyad'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_now',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tarih - Saat'),
        ),
    ]
